#! /bin/sh

killall sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# bash ~/.config/polybar/launch.sh --colorblocks
bash ~/.config/polybar/launch.sh --blocks
picom --experimental-backends -b &
./.fehbg &
nm-applet &
dunst &
xfce-polkit &
xss-lock --transfer-sleep-lock -- blurlock --nofork &


bspc monitor -d  'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII' 'IX' 'X'

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 0
bspc config bottom_padding 0
bspc config focused_border_color "#aed1dc"
bspc config normal_border_color  "#4c566a"
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


### BIND TO WORKSPACE
bspc rule -a Brave-browser desktop='^2'
bspc rule -a Emacs desktop='^8' state=tiled follow=on
bspc rule -a Screenkey manage=off
bspc rule -a discord desktop='^4' state=tiled follow=off
bspc rule -a zoom desktop='^9' state=monocle
bspc rule -a "Microsoft Teams - Preview" desktop='^9' state=monocle
bspc rule -a Thunar desktop='^6'
bspc rule -a Pavucontrol desktop='^8'
bspc rule -a Zathura desktop='^3'
bspc rule -a Evince desktop='^3'
bspc rule -a Mailspring desktop='^3'
bspc rule -a Firefox desktop='^5' state=tiled

xdo lower -N "Polybar"
xdo above -N "Polybar" -t $(xdo id -N Bspwm -n root)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)

